# Generated by Django 3.2 on 2022-04-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautypal', '0003_auto_20220330_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
